name = "Test"

[files]
"main.py" = "./main.py"
"esp32_driver.py" = "./esp32_driver.py"
"control_panel.py" = "./control_panel.py"
"RS232.py" = "./RS232.py"

[js_modules.main]
"https://cdn.jsdelivr.net/npm/micro-repl@0.8.2/serial.js" = "micro_repl"